# Generated by Django 4.2.5 on 2023-10-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_alter_pedidosexames_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidosexames',
            options={'verbose_name_plural': 'Pedidos exames'},
        ),
    ]
