# Generated by Django 4.2.5 on 2023-10-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_alter_pedidosexames_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposexames',
            options={'verbose_name_plural': 'Tipos exames'},
        ),
    ]
